language: node_js
node_js:
  - "6"
notifications:
  email: false
install:
  npm install
cache:
  directories:
    - node_modules 
script:
  npm run build
deploy:
  provider: surge
  project: ./dist/
  domain: cauhoi.cunghoctot.net
release:
  - exit 0  