language: node_js
node_js:
  - "6"
notifications:
  email: false
before_install:
  npm install -g surge
install:
  npm install
script:
  npm run build
after_success:
  - surge --project ./dist --domain nhch.surge.sh
release:
  - exit 0  