language: node_js
node_js:
  - "6"
notifications:
  email: false
before_install:
  npm install --save-dev surge
install:
  npm install
cache:
  directories:
    - node_modules
script:
  npm run build
release:
  - exit 0  